import type { LucideIcon } from 'lucide-react'
import { Trophy, Award, Medal, Crown, Star, Sparkles, BadgeCheck, Gem, Diamond, Flame, ThumbsUp, PartyPopper, Gift, Ribbon, Heart, HeartHandshake, Handshake, Users, User, Smile, Music, Music4, Mic, Disc3, Guitar, Piano, Drum, Headphones, Radio, Speaker, ListMusic, AudioLines, Film, Clapperboard, Video, Camera, Image, Images, Tv, MonitorPlay, Play, Drama, Aperture, Palette, Brush, PenTool, Pencil, Feather, Shapes, Book, BookOpen, GraduationCap, Library, Newspaper, ScrollText, Globe, MapPin, Map, Plane, Rocket, Compass, Anchor, Ship, Mountain, Landmark, Building2, Flag, TentTree, Sun, Moon, Cloud, Snowflake, Leaf, Trees, Flower, Sprout, Rainbow, Droplet, Wind, Dog, Cat, Bird, Fish, Rabbit, PawPrint, Bug, Turtle, Coffee, Cake, Pizza, Utensils, Cookie, Apple, Wine, CupSoda, Dumbbell, Bike, Target, Swords, Zap, Activity, HeartPulse, Footprints, Gamepad2, Dice5, Puzzle, Lightbulb, Key, Lock, ShieldCheck, Bell, Bookmark, Calendar, Clock, Timer, TrendingUp, DollarSign, Coins, Wallet, ShoppingBag, Tag, Ticket, Megaphone, Quote, MessageCircle, Hash, AtSign, Link } from 'lucide-react'

/** Курируемая библиотека монохромных SVG-иконок (lucide) для блока «Плашки».
 *  Значение awards.icon хранит ключ (имя иконки). Старые эмодзи — текст-фолбэк. */
export type AwardIcon = { key: string; label: string; Comp: LucideIcon }

export const AWARD_ICONS: AwardIcon[] = [
  { key: 'Trophy', label: 'кубок награда', Comp: Trophy },
  { key: 'Award', label: 'награда медаль', Comp: Award },
  { key: 'Medal', label: 'медаль', Comp: Medal },
  { key: 'Crown', label: 'корона', Comp: Crown },
  { key: 'Star', label: 'звезда', Comp: Star },
  { key: 'Sparkles', label: 'блеск искры', Comp: Sparkles },
  { key: 'BadgeCheck', label: 'знак проверено', Comp: BadgeCheck },
  { key: 'Gem', label: 'самоцвет', Comp: Gem },
  { key: 'Diamond', label: 'бриллиант', Comp: Diamond },
  { key: 'Flame', label: 'огонь пламя', Comp: Flame },
  { key: 'ThumbsUp', label: 'лайк палец', Comp: ThumbsUp },
  { key: 'PartyPopper', label: 'праздник хлопушка', Comp: PartyPopper },
  { key: 'Gift', label: 'подарок', Comp: Gift },
  { key: 'Ribbon', label: 'лента', Comp: Ribbon },
  { key: 'Heart', label: 'сердце', Comp: Heart },
  { key: 'HeartHandshake', label: 'поддержка сердце', Comp: HeartHandshake },
  { key: 'Handshake', label: 'рукопожатие', Comp: Handshake },
  { key: 'Users', label: 'люди группа', Comp: Users },
  { key: 'User', label: 'человек', Comp: User },
  { key: 'Smile', label: 'улыбка', Comp: Smile },
  { key: 'Music', label: 'музыка', Comp: Music },
  { key: 'Music4', label: 'ноты музыка', Comp: Music4 },
  { key: 'Mic', label: 'микрофон', Comp: Mic },
  { key: 'Disc3', label: 'диск альбом', Comp: Disc3 },
  { key: 'Guitar', label: 'гитара', Comp: Guitar },
  { key: 'Piano', label: 'пианино', Comp: Piano },
  { key: 'Drum', label: 'барабан', Comp: Drum },
  { key: 'Headphones', label: 'наушники', Comp: Headphones },
  { key: 'Radio', label: 'радио', Comp: Radio },
  { key: 'Speaker', label: 'колонка', Comp: Speaker },
  { key: 'ListMusic', label: 'плейлист', Comp: ListMusic },
  { key: 'AudioLines', label: 'звук волны', Comp: AudioLines },
  { key: 'Film', label: 'фильм кино', Comp: Film },
  { key: 'Clapperboard', label: 'хлопушка кино', Comp: Clapperboard },
  { key: 'Video', label: 'видео', Comp: Video },
  { key: 'Camera', label: 'камера фото', Comp: Camera },
  { key: 'Image', label: 'изображение', Comp: Image },
  { key: 'Images', label: 'галерея', Comp: Images },
  { key: 'Tv', label: 'тв экран', Comp: Tv },
  { key: 'MonitorPlay', label: 'экран плей', Comp: MonitorPlay },
  { key: 'Play', label: 'воспроизвести', Comp: Play },
  { key: 'Drama', label: 'театр маски', Comp: Drama },
  { key: 'Aperture', label: 'диафрагма', Comp: Aperture },
  { key: 'Palette', label: 'палитра', Comp: Palette },
  { key: 'Brush', label: 'кисть', Comp: Brush },
  { key: 'PenTool', label: 'перо', Comp: PenTool },
  { key: 'Pencil', label: 'карандаш', Comp: Pencil },
  { key: 'Feather', label: 'перо', Comp: Feather },
  { key: 'Shapes', label: 'фигуры', Comp: Shapes },
  { key: 'Book', label: 'книга', Comp: Book },
  { key: 'BookOpen', label: 'книга открытая', Comp: BookOpen },
  { key: 'GraduationCap', label: 'диплом выпускной', Comp: GraduationCap },
  { key: 'Library', label: 'библиотека', Comp: Library },
  { key: 'Newspaper', label: 'газета', Comp: Newspaper },
  { key: 'ScrollText', label: 'свиток', Comp: ScrollText },
  { key: 'Globe', label: 'глобус мир', Comp: Globe },
  { key: 'MapPin', label: 'метка гео', Comp: MapPin },
  { key: 'Map', label: 'карта', Comp: Map },
  { key: 'Plane', label: 'самолёт', Comp: Plane },
  { key: 'Rocket', label: 'ракета', Comp: Rocket },
  { key: 'Compass', label: 'компас', Comp: Compass },
  { key: 'Anchor', label: 'якорь', Comp: Anchor },
  { key: 'Ship', label: 'корабль', Comp: Ship },
  { key: 'Mountain', label: 'гора', Comp: Mountain },
  { key: 'Landmark', label: 'достопримечательность', Comp: Landmark },
  { key: 'Building2', label: 'здание', Comp: Building2 },
  { key: 'Flag', label: 'флаг', Comp: Flag },
  { key: 'TentTree', label: 'кемпинг', Comp: TentTree },
  { key: 'Sun', label: 'солнце', Comp: Sun },
  { key: 'Moon', label: 'луна', Comp: Moon },
  { key: 'Cloud', label: 'облако', Comp: Cloud },
  { key: 'Snowflake', label: 'снежинка', Comp: Snowflake },
  { key: 'Leaf', label: 'лист', Comp: Leaf },
  { key: 'Trees', label: 'деревья', Comp: Trees },
  { key: 'Flower', label: 'цветок', Comp: Flower },
  { key: 'Sprout', label: 'росток', Comp: Sprout },
  { key: 'Rainbow', label: 'радуга', Comp: Rainbow },
  { key: 'Droplet', label: 'капля', Comp: Droplet },
  { key: 'Wind', label: 'ветер', Comp: Wind },
  { key: 'Dog', label: 'собака', Comp: Dog },
  { key: 'Cat', label: 'кошка', Comp: Cat },
  { key: 'Bird', label: 'птица', Comp: Bird },
  { key: 'Fish', label: 'рыба', Comp: Fish },
  { key: 'Rabbit', label: 'кролик', Comp: Rabbit },
  { key: 'PawPrint', label: 'лапа след', Comp: PawPrint },
  { key: 'Bug', label: 'жук', Comp: Bug },
  { key: 'Turtle', label: 'черепаха', Comp: Turtle },
  { key: 'Coffee', label: 'кофе', Comp: Coffee },
  { key: 'Cake', label: 'торт', Comp: Cake },
  { key: 'Pizza', label: 'пицца', Comp: Pizza },
  { key: 'Utensils', label: 'еда столовые', Comp: Utensils },
  { key: 'Cookie', label: 'печенье', Comp: Cookie },
  { key: 'Apple', label: 'яблоко', Comp: Apple },
  { key: 'Wine', label: 'вино', Comp: Wine },
  { key: 'CupSoda', label: 'напиток', Comp: CupSoda },
  { key: 'Dumbbell', label: 'гантель спорт', Comp: Dumbbell },
  { key: 'Bike', label: 'велосипед', Comp: Bike },
  { key: 'Target', label: 'цель мишень', Comp: Target },
  { key: 'Swords', label: 'мечи бой', Comp: Swords },
  { key: 'Zap', label: 'молния', Comp: Zap },
  { key: 'Activity', label: 'активность пульс', Comp: Activity },
  { key: 'HeartPulse', label: 'пульс', Comp: HeartPulse },
  { key: 'Footprints', label: 'шаги следы', Comp: Footprints },
  { key: 'Gamepad2', label: 'игра джойстик', Comp: Gamepad2 },
  { key: 'Dice5', label: 'кубик игра', Comp: Dice5 },
  { key: 'Puzzle', label: 'пазл', Comp: Puzzle },
  { key: 'Lightbulb', label: 'идея лампа', Comp: Lightbulb },
  { key: 'Key', label: 'ключ', Comp: Key },
  { key: 'Lock', label: 'замок', Comp: Lock },
  { key: 'ShieldCheck', label: 'щит защита', Comp: ShieldCheck },
  { key: 'Bell', label: 'колокол', Comp: Bell },
  { key: 'Bookmark', label: 'закладка', Comp: Bookmark },
  { key: 'Calendar', label: 'календарь', Comp: Calendar },
  { key: 'Clock', label: 'часы', Comp: Clock },
  { key: 'Timer', label: 'таймер', Comp: Timer },
  { key: 'TrendingUp', label: 'рост график', Comp: TrendingUp },
  { key: 'DollarSign', label: 'доллар деньги', Comp: DollarSign },
  { key: 'Coins', label: 'монеты', Comp: Coins },
  { key: 'Wallet', label: 'кошелёк', Comp: Wallet },
  { key: 'ShoppingBag', label: 'покупки', Comp: ShoppingBag },
  { key: 'Tag', label: 'тег ярлык', Comp: Tag },
  { key: 'Ticket', label: 'билет', Comp: Ticket },
  { key: 'Megaphone', label: 'рупор анонс', Comp: Megaphone },
  { key: 'Quote', label: 'цитата', Comp: Quote },
  { key: 'MessageCircle', label: 'сообщение', Comp: MessageCircle },
  { key: 'Hash', label: 'хэштег', Comp: Hash },
  { key: 'AtSign', label: 'собака почта', Comp: AtSign },
  { key: 'Link', label: 'ссылка', Comp: Link },
]

export const AWARD_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(AWARD_ICONS.map((i) => [i.key, i.Comp]))
