/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    subscribers: SubscriberAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'site-settings': SiteSetting;
    categories: Category;
    publications: Publication;
    pages: Page;
    'menu-items': MenuItem;
    media: Media;
    'subscription-tiers': SubscriptionTier;
    subscribers: Subscriber;
    videos: Video;
    'video-folders': VideoFolder;
    'gallery-images': GalleryImage;
    'gallery-folders': GalleryFolder;
    comments: Comment;
    reactions: Reaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'subscription-tiers': SubscriptionTiersSelect<false> | SubscriptionTiersSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'video-folders': VideoFoldersSelect<false> | VideoFoldersSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'gallery-folders': GalleryFoldersSelect<false> | GalleryFoldersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    counters: CountersWidget;
    quickActions: QuickActionsWidget;
    recentPublications: RecentPublicationsWidget;
    collections: CollectionsWidget;
  };
  user: User | Subscriber;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SubscriberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Полный домен, напр. bts.example.com
   */
  domain: string;
  domainVerified?: boolean | null;
  status: 'pending' | 'active' | 'suspended';
  plan?: ('free' | 'basic' | 'pro') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Пусто для платформенных пользователей (superadmin).
   */
  tenant?: (number | null) | Tenant;
  /**
   * Только для платформенных пользователей.
   */
  platformRole?: 'superadmin' | null;
  tenantRole?: ('editor' | 'admin' | 'viewer') | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  logo?: (number | null) | Media;
  theme?: {
    /**
     * напр. #7C3AED
     */
    primary?: string | null;
    accent?: string | null;
    background?: string | null;
    surface?: string | null;
    text?: string | null;
  };
  typography?: {
    headingFont?: ('inter' | 'montserrat' | 'manrope' | 'golos' | 'ptsans' | 'unbounded' | 'roboto') | null;
    bodyFont?: ('inter' | 'montserrat' | 'manrope' | 'golos' | 'ptsans' | 'roboto') | null;
    textSize?: ('18' | '20' | '22' | '24') | null;
    textWeight?: ('300' | '400') | null;
    headingWeight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  /**
   * Если список участников пуст — блок не отображается.
   */
  heroTeam?: {
    members?:
      | {
          photo: number | Media;
          /**
           * Для alt-текста.
           */
          name?: string | null;
          /**
           * Клик по аватару ведёт на эту категорию. Можно оставить пустым.
           */
          category?: (number | null) | Category;
          id?: string | null;
        }[]
      | null;
    /**
     * Текст справа от аватаров. Переносы строк сохраняются.
     */
    caption?: string | null;
    avatarSize?: ('48' | '64' | '96' | '128') | null;
  };
  /**
   * Тексты верхнего блока главной. Если поля пустые — показываются значения по умолчанию.
   */
  hero?: {
    /**
     * Мелкая надпись-бейдж над слоганом. Пусто — значение по умолчанию.
     */
    eyebrow?: string | null;
    /**
     * Каждая строка — отдельная строка заголовка. Последняя строка выделяется градиентом. Пусто — значение по умолчанию.
     */
    titleLines?: string | null;
  };
  /**
   * Чипсы под заголовком главной. Порядок задаётся перетаскиванием.
   */
  heroChips?: (number | Category)[] | null;
  /**
   * Блок «Категории». Если пусто — блок не отображается.
   */
  homeCategories?: (number | Category)[] | null;
  /**
   * Порядок и видимость секций главной. Порядок задаётся перетаскиванием. Если список пуст — показываются все секции в порядке по умолчанию. Секции, зависящие от данных (участники, категории), скрываются автоматически при отсутствии данных, даже если включены.
   */
  homeSections?:
    | {
        type:
          | 'hero'
          | 'heroTeam'
          | 'news'
          | 'latest'
          | 'popular'
          | 'discussed'
          | 'posterRows'
          | 'categories'
          | 'popularCategories'
          | 'whyUs'
          | 'socials'
          | 'broadcast';
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Тексты финального баннера главной. Если поля пустые — показываются значения по умолчанию.
   */
  banner?: {
    /**
     * Мелкая надпись над «ON AIR». Пусто — значение по умолчанию.
     */
    tagline?: string | null;
    /**
     * Крупная неоновая надпись. Пусто — значение по умолчанию.
     */
    onAirText?: string | null;
  };
  socials?:
    | {
        platform: 'boosty' | 'vk' | 'telegram' | 'youtube' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  seoDefaults?: {
    /**
     * напр. "%s — COCO JAMBO"
     */
    titleTemplate?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  navigation?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    text?: string | null;
    copyright?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Дискография > Chapter 1 > School Trilogy
   */
  fullTitle?: string | null;
  cover?: (number | null) | Media;
  /**
   * Текст над списком публикаций. Можно оставить пустым.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  /**
   * Только для категорий верхнего уровня.
   */
  showInHeader?: boolean | null;
  /**
   * Показывать в колонке футера (для подкатегорий 2-го уровня).
   */
  showInFooter?: boolean | null;
  /**
   * Публикации этой категории показываются горизонтальным рядом вертикальных постеров 2:3 (как афиши фильмов) — на странице категории и на главной. Загружайте вертикальную обложку.
   */
  posterLayout?: boolean | null;
  /**
   * Пусто = сгенерируется автоматически из названия и описания при сохранении.
   */
  seo?: {
    /**
     * Рекомендуется до 60 символов.
     */
    title?: string | null;
    /**
     * Рекомендуется до 160 символов.
     */
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Ключевые поисковые запросы для этой страницы. Заполняется вручную или импортом из Wordstat.
     */
    targetKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  cover?: (number | null) | Media;
  publishedAt?: string | null;
  category?: (number | null) | Category;
  /**
   * Пусто = доступно всем бесплатно. Иначе — от этого уровня и выше.
   */
  minTier?: (number | null) | SubscriptionTier;
  /**
   * Видео, показываемые в публикации (до описания). Доступ каждого — по его собственному уровню.
   */
  relatedVideos?: (number | Video)[] | null;
  /**
   * Фото-галерея публикации. Доступна по уровню самой публикации (minTier).
   */
  gallery?:
    | {
        image: number | GalleryImage;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sources?:
    | {
        type: 'external' | 'hosted';
        platform?: ('boosty' | 'vk' | 'telegram' | 'youtube') | null;
        url?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Отметьте, если это новость о событиях во вселенной BTS. Такие материалы попадают в секцию «Новости» на главной.
   */
  isNews?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Уровни подписки и их настройки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-tiers".
 */
export interface SubscriptionTier {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Латиницей: ramyeon, soju, samgyeopsal.
   */
  slug: string;
  /**
   * Чем больше, тем выше уровень. Высший уровень открывает контент низших.
   */
  weight: number;
  priceRub: number;
  /**
   * Краткое описание преимуществ уровня.
   */
  description?: string | null;
  /**
   * Неактивные уровни не показываются для оформления.
   */
  isActive?: boolean | null;
  /**
   * Список преимуществ уровня для витрины подписки. Иконка задаётся типом.
   */
  perks?:
    | {
        type: 'included' | 'star' | 'warning' | 'info';
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Видеоконтент с доступом по уровню подписки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  description?: string | null;
  cover?: (number | null) | Media;
  /**
   * Раздел дерева: weverse-live, концерты, участник...
   */
  category?: (number | null) | Category;
  /**
   * Папка для группировки видео в студии. Одно видео — одна папка.
   */
  folder?: (number | null) | VideoFolder;
  /**
   * Пусто = доступно всем бесплатно. Иначе — от этого уровня и выше.
   */
  minTier?: (number | null) | SubscriptionTier;
  /**
   * Открыто всем, даже без подписки (перебивает minTier).
   */
  isPreview?: boolean | null;
  /**
   * Где хранится видео. Stream — для зарубежной аудитории; Kinescope — для РФ (не блокируется провайдерами).
   */
  provider: 'stream' | 'kinescope';
  /**
   * Идентификатор видео в хранилище: CF Stream uid или Kinescope video_id (по provider).
   */
  videoRef?: string | null;
  durationSec?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Папки для группировки видео (дерево).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-folders".
 */
export interface VideoFolder {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  parent?: (number | null) | VideoFolder;
  breadcrumbs?:
    | {
        doc?: (number | null) | VideoFolder;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Фото для галерей публикаций.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  /**
   * Папка библиотеки для группировки. Одно изображение — одна папка.
   */
  folder?: (number | null) | GalleryFolder;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Папки для группировки изображений (дерево).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-folders".
 */
export interface GalleryFolder {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  parent?: (number | null) | GalleryFolder;
  breadcrumbs?:
    | {
        doc?: (number | null) | GalleryFolder;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Текстовые страницы сайта — редактируются клиентом.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Отображается как H1 и в меню.
   */
  title: string;
  /**
   * Адрес страницы: /page/about, /page/faq и т.д.
   */
  slug: string;
  /**
   * Тело страницы. Форматирование как в редакторе.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showInMenu?: boolean | null;
  showInFooter?: boolean | null;
  /**
   * Сортировка в меню/футере.
   */
  menuOrder?: number | null;
  /**
   * В какой колонке футера показывать страницу.
   */
  footerColumn?: ('nav' | 'support') | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Ручные правки меню поверх автогенерации из категорий.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  tenant?: (number | null) | Tenant;
  location: 'header' | 'footer';
  kind: 'category' | 'page' | 'url';
  /**
   * Оверрайд авто-узла категории.
   */
  category?: (number | null) | Category;
  /**
   * Пункт ведёт на страницу («О проекте» и т.п.).
   */
  page?: (number | null) | Page;
  /**
   * Абсолютная ссылка: https://…
   */
  url?: string | null;
  /**
   * Пусто — берётся имя категории/страницы. Для URL обязательно.
   */
  labelOverride?: string | null;
  /**
   * Скрыть узел из меню, не удаляя запись.
   */
  hidden?: boolean | null;
  /**
   * Пункт-родитель для вложенности. Пусто — корневой уровень.
   */
  parent?: (number | null) | MenuItem;
  /**
   * Сортировка внутри своего уровня.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Все зарегистрированные зрители, включая бесплатных.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  tenant?: (number | null) | Tenant;
  displayName?: string | null;
  /**
   * Пусто = бесплатный аккаунт без подписки.
   */
  activeTier?: (number | null) | SubscriptionTier;
  /**
   * Дата окончания текущей оплаченной подписки.
   */
  subscriptionUntil?: string | null;
  isBlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'subscribers';
}
/**
 * Комментарии зрителей. Постмодерация: скрывайте нарушающие через статус.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  tenant?: (number | null) | Tenant;
  publication: number | Publication;
  /**
   * Зритель, оставивший комментарий.
   */
  author: number | Subscriber;
  text: string;
  /**
   * Заполнено = это ответ. Ветки только один уровень.
   */
  parent?: (number | null) | Comment;
  /**
   * Скрытые комментарии не видны на сайте.
   */
  status: 'published' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * Эмодзи-реакции зрителей на публикации и комментарии.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  tenant?: (number | null) | Tenant;
  targetType: 'publication' | 'comment';
  /**
   * Заполнено при targetType = публикация.
   */
  publication?: (number | null) | Publication;
  /**
   * Заполнено при targetType = комментарий.
   */
  comment?: (number | null) | Comment;
  subscriber: number | Subscriber;
  emoji: 'like' | 'love' | 'fire' | 'cry';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscription-tiers';
        value: number | SubscriptionTier;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'video-folders';
        value: number | VideoFolder;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'gallery-folders';
        value: number | GalleryFolder;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'subscribers';
        value: number | Subscriber;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'subscribers';
        value: number | Subscriber;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  domainVerified?: T;
  status?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  platformRole?: T;
  tenantRole?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  logo?: T;
  theme?:
    | T
    | {
        primary?: T;
        accent?: T;
        background?: T;
        surface?: T;
        text?: T;
      };
  typography?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
        textSize?: T;
        textWeight?: T;
        headingWeight?: T;
      };
  heroTeam?:
    | T
    | {
        members?:
          | T
          | {
              photo?: T;
              name?: T;
              category?: T;
              id?: T;
            };
        caption?: T;
        avatarSize?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLines?: T;
      };
  heroChips?: T;
  homeCategories?: T;
  homeSections?:
    | T
    | {
        type?: T;
        enabled?: T;
        id?: T;
      };
  banner?:
    | T
    | {
        tagline?: T;
        onAirText?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seoDefaults?:
    | T
    | {
        titleTemplate?: T;
        description?: T;
        ogImage?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        text?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  fullTitle?: T;
  cover?: T;
  description?: T;
  order?: T;
  showInHeader?: T;
  showInFooter?: T;
  posterLayout?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        targetKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  cover?: T;
  publishedAt?: T;
  category?: T;
  minTier?: T;
  relatedVideos?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  description?: T;
  sources?:
    | T
    | {
        type?: T;
        platform?: T;
        url?: T;
        media?: T;
        id?: T;
      };
  featured?: T;
  isNews?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  content?: T;
  showInMenu?: T;
  showInFooter?: T;
  menuOrder?: T;
  footerColumn?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  tenant?: T;
  location?: T;
  kind?: T;
  category?: T;
  page?: T;
  url?: T;
  labelOverride?: T;
  hidden?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-tiers_select".
 */
export interface SubscriptionTiersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  weight?: T;
  priceRub?: T;
  description?: T;
  isActive?: T;
  perks?:
    | T
    | {
        type?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  tenant?: T;
  displayName?: T;
  activeTier?: T;
  subscriptionUntil?: T;
  isBlocked?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  cover?: T;
  category?: T;
  folder?: T;
  minTier?: T;
  isPreview?: T;
  provider?: T;
  videoRef?: T;
  durationSec?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-folders_select".
 */
export interface VideoFoldersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-folders_select".
 */
export interface GalleryFoldersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  tenant?: T;
  publication?: T;
  author?: T;
  text?: T;
  parent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  tenant?: T;
  targetType?: T;
  publication?: T;
  comment?: T;
  subscriber?: T;
  emoji?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters_widget".
 */
export interface CountersWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quickActions_widget".
 */
export interface QuickActionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recentPublications_widget".
 */
export interface RecentPublicationsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}